### ISSUE TITLE
bug: couldn't compile with ImGui 1.91.9

### ISSUE THREAD

**Issue by CosminPerRam** [SFML/imgui-sfml#319]
Upon using `v3.0` and ImGui `1.91.9` I encounter these compilation errors:
```
D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(779,12): error C2661: 'ImGui::Image': no overloaded function takes 6 arguments [D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-build\ImGui-SFML.vcxproj]
  D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(779,12):
  while trying to match the argument list '(ImTextureID, ImVec2, ImVec2, ImVec2, ImColor, ImColor)'

D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(792,12): error C2661: 'ImGui::Image': no overloaded function takes 6 arguments [D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-build\ImGui-SFML.vcxproj]
  D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(792,12):
  while trying to match the argument list '(ImTextureID, ImVec2, ImVec2, ImVec2, ImColor, ImColor)'

D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(813,12): error C2661: 'ImGui::Image': no overloaded function takes 6 arguments [D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-build\ImGui-SFML.vcxproj]
  D:\GitHub\StylishVisualizer\build\_deps\imgui-sfml-src\imgui-SFML.cpp(813,12):
  while trying to match the argument list '(ImTextureID, ImVec2, ImVec2, ImVec2, ImColor, ImColor)'
```
Code references (in order of error messages):
https://github.com/SFML/imgui-sfml/blob/070d6ab9aa98c997b1fa846175d3faf93de3866e/imgui-SFML.cpp#L779
https://github.com/SFML/imgui-sfml/blob/070d6ab9aa98c997b1fa846175d3faf93de3866e/imgui-SFML.cpp#L792-L800
https://github.com/SFML/imgui-sfml/blob/070d6ab9aa98c997b1fa846175d3faf93de3866e/imgui-SFML.cpp#L813

Which seems to be due to breakage of ImGui::Image API:

![Image](https://github.com/user-attachments/assets/30f7a071-523e-40e1-97d5-1aaf0810876e)

Using a version prior to this one compiles with no problems.
Thanks!

**Comment by ChrisThrasher** [comment]
Are you building with `IMGUI_DISABLE_OBSOLETE_FUNCTIONS` enabled?

**Comment by CosminPerRam** [comment]
Oops, I indeed was, closing this as solved then.
Would it be worth to add this somewhere in the docs?
